/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/w38COtgVxyl
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex flex-col md:flex-row items-center justify-center gap-4 md:gap-8 w-full h-full p-4 md:p-8">
      <Card className="w-full md:w-1/2 max-w-lg">
        <CardHeader>
          <CardTitle>Enter Your Card Details</CardTitle>
          <CardDescription>Securely enter your payment information.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="cardNumber">Card Number</Label>
            <Input id="cardNumber" placeholder="1234 5678 9012 3456" type="text" />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="expiryDate">Expiry Date</Label>
              <Input id="expiryDate" placeholder="MM/YY" type="text" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="cvv">CVV</Label>
              <Input id="cvv" placeholder="123" type="text" />
            </div>
          </div>
        </CardContent>
        <CardFooter>
          <Button className="ml-auto">Submit</Button>
        </CardFooter>
      </Card>
      <div className="w-full md:w-1/2 max-w-lg">
        <img
          alt="Credit Card"
          className="w-full h-auto object-cover rounded-lg"
          height="200"
          src="/placeholder.svg"
          style={{
            aspectRatio: "300/200",
            objectFit: "cover",
          }}
          width="300"
        />
      </div>
    </div>
  )
}
